apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: pipelines-test
      annotations:
        openshift.io/description: "Openshift Pipelines namespace"
        openshift.io/display-name: "Pipelines Testing Project"