apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: copy-secrets
  namespace: pipelines-test
spec:
  params:
    - name: secret
      description: Name of the secret to copy.
      type: string
      default: this-is-a-new-secret
    - name: origin-namespace
      description: Namespace that contains the secret.
      type: string
      default: pipelines-test
    - name: destination-namespace
      description: Namespace in which we want the secret to be copied.
      type: string
      default: new-project
  steps:
    - name: copy-secrets
      # image: registry.access.redhat.com/ubi8/ubi
      image: quay.io/dgarciap/openshift-pipelines:latest
      script: |
        #!/bin/sh
        echo "Starting task."
        oc get secret $(params.secret) -n $(params.origin-namespace) -o yaml | sed 's/namespace: .*/namespace: $(params.destination-namespace)/' | oc apply -f -